version: '2'
services:

 php:
  image: quentinv/phpservermonitor
  restart: always
  networks:
   - network
  ports:
   - 80:80

 mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
    networks:
     - network
    restart: always


 phpmyadmin:
    image: corbinu/docker-phpmyadmin
    environment:
     - MYSQL_USERNAME=root
     - MYSQL_PASSWORD=YOUR_PASSWORD
     - MYSQL_PORT_3306_TCP_ADDR=NAME_MYSQL_CONTAINERs
    ports:
     - 81:80    
    networks:
     - network 

networks:
  network:
   driver: bridge